server:
  port: 8000
  servlet:
    context-path: /rentacar/api
spring:
  application:
    name: rentacar
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar
    username: postgres
    password: postdba
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: false
springdoc:
  api-docs:
    path: /docs
    pathsToMatch: /api/**
  swagger-ui:
    path: /swagger

