INSERT INTO brands (name, description) VALUES
   ('Toyota', 'Montadora japonesa confiável'),
   ('Ford', 'Marca americana tradicional'),
   ('Chevrolet', 'Divisão da General Motors'),
   ('Volkswagen', 'Montadora alemã popular'),
   ('Honda', 'Marca japonesa de alta qualidade'),
   ('Hyundai', 'Fabricante sul-coreana moderna'),
   ('Nissan', 'Montadora japonesa inovadora'),
   ('BMW', 'Marca alemã de luxo'),
   ('Mercedes-Benz', 'Luxo e tecnologia alemã'),
   ('Audi', 'Marca premium da Volkswagen'),
   ('Kia', 'Montadora sul-coreana crescente'),
   ('Peugeot', 'Fabricante francesa elegante'),
   ('Renault', 'Marca francesa consolidada'),
   ('Fiat', 'Montadora italiana popular'),
   ('Jeep', 'Especialista em veículos off-road'),
   ('Volvo', 'Segurança e tecnologia sueca'),
   ('Mitsubishi', 'Marca japonesa versátil'),
   ('Subaru', 'Famosa por tração integral'),
   ('Land Rover', 'SUVs de luxo britânicos'),
   ('Porsche', 'Esportivos alemães de alto desempenho');